services:
  hubminimalwp:
    build: .
    container_name: HubMinimalWp
    restart: unless-stopped
    environment:
      PORT: "3000"
      API_KEY: ${API_KEY:-}
    volumes:
      - /datastore/hubminimal/data:/app/data
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.wa.rule=Host(`wa.octotech.az`)'
      - 'traefik.http.routers.wa.entrypoints=websecure'
      - 'traefik.http.routers.wa.priority=100'
      - 'traefik.http.services.wa.loadbalancer.server.port=3000'

networks:
  edge:
    external: true
